### ISSUE TITLE
Using neovim within flatten.nvim to edit long commands?

### ISSUE THREAD

**Issue by imochoa** [willothy/flatten.nvim#15]
# Context
## Using neovim to edit a command in the **normal shell**
You can set neovim as the `VISUAL` environment variable so that pressing `<C-x><C-e>` opens it in neovim for editting:
> It's a "bash" thing that's common in other shells as well. In the bash man-page, it's explained like this:
>
> Invoke an editor on the current command line, and execute the result as shell commands. Bash attempts to invoke $VISUAL, $EDITOR, and emacs as the editor, in that order.

It looks something like this:
[![](https://markdown-videos.deta.dev/youtube/bqlTZMbwUlA)](https://youtu.be/bqlTZMbwUlA)

## Using neovim to edit a command in the **embedded neovim terminal shell**
If you use [neovim-remote](https://github.com/mhinz/neovim-remote) you can detect when your shell is running within neovim and set `VISUAL` to be `nvr -cc tabedit --remote-wait +'set bufhidden=wipe'`. That way, instead of launching a nested neovim instance it will use the existing neovim instance to edit the command in a separate tab, inserting it on "save"
> I got this from ["Modern Vim" Tip 22 Using an Existing nvim Instance as the Preferred Editor](https://books.google.de/books?id=o-FdDwAAQBAJ&pg=PT151&lpg=PT151&dq=neovim+%22%3CC-x%3E%3Cc-e%3E%22+mapping&source=bl&ots=FlHavfHb9O&sig=ACfU3U28pFtikrG_Du649gyW24oR6LG6hQ&hl=de&sa=X&ved=2ahUKEwjX9K_6huD9AhVRPOwKHTd-BogQ6AF6BAgJEAE#v=onepage&q&f=false), although it's a common practice

# Question
If you try this with the default config and `VISUAL=nvim`, saving the edited command exits neovim completely:
[![](https://markdown-videos.deta.dev/youtube/nh_WAvCo-Ho)](https://youtu.be/nh_WAvCo-Ho)

So I was wondering whether it would be possible to have the same neovim-remote behavior with `flatten.nvim` i.e. opening the long command in a separate buffer for editing and recover it on save (`:wq`)

Perhaps one approach would be to mess with the `VISUAL` env var as well, or remapping the `<C-x><C-e>` keypress?

**Comment by willothy** [comment]
Alright, I think I have a better idea of this now, I'll start looking into a solution. Btw the videos are private, would you mind marking them as unlisted so I'm able to view them? Thanks!

**Comment by imochoa** [comment]
Ah indeed, I fixed the links and added a link to the chapter of the book I referenced.

I also found another plugin whose sole purpose is to handle this situation: [nvim-editcommand](https://github.com/brettanomyces/nvim-editcommand)
![image](https://user-images.githubusercontent.com/18612100/225563404-c0a2fa4c-89af-400d-a3b2-a35850eac93d.png)


I'll use that for now, but I still think it could be a nice feature for your plugin as well 😬

**Comment by willothy** [comment]
@imochoa The `edit-exec` branch should work, would you mind trying it out before I merge?

**Comment by imochoa** [comment]
Sorry for the delay, I was moving this weekend 😅
I just tested it and it works, thanks! That's really cool, now there's no need to mess around with neovim-remote as far as I'm concerned :)

By the way, I tested with both:
- `VISUAL="nvim"`
- `VISUAL="nvim --cmd 'let g:flatten_wait=1'"`
and I did not notice a difference in behavior between them

**Comment by willothy** [comment]
No worries! Not sure why that would be, it's required for me unless the filetype is set to block in the config, but if it works it works :)
