### ISSUE TITLE
`invalid escape sequence near ''\.'` on Windows

### ISSUE THREAD

**Issue by luiz00martins** [willothy/flatten.nvim#18]
**Describe the bug**
While using flatten.nvim on Windows with the example configuration for toggleterm shown on the README, it returns the following error:

```
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: Vim:Error invoking 'nvim_exec_lua' on channel 3:
Error loading lua: [string "<nvim>"]:3: invalid escape sequence near ''\.'
stack traceback:
        [C]: in function 'rpcrequest'
        .../Local/nvim-data/lazy/flatten.nvim/lua/flatten/guest.lua:19: in function 'send_files'
        .../Local/nvim-data/lazy/flatten.nvim/lua/flatten/guest.lua:56: in function <.../Local/nvim-data/lazy/flatten.nvim/lua/flatten/guest.lua:51>
```

**To Reproduce**
1. Use the following config:
```lua
opts = {
		callbacks = {
				pre_open = function()
						-- Close toggleterm when an external open request is received
						require("toggleterm").toggle(0)
				end,
				post_open = function(bufnr, winnr, ft)
						if ft == "gitcommit" then
								-- If the file is a git commit, create one-shot autocmd to delete it on write
								-- If you just want the toggleable terminal integration, ignore this bit and only use the
								-- code in the else block
								vim.api.nvim_create_autocmd(
										"BufWritePost",
										{
												buffer = bufnr,
												once = true,
												callback = function()
														-- This is a bit of a hack, but if you run bufdelete immediately 
														-- the shell can occasionally freeze
														vim.defer_fn(
																function()
																		vim.api.nvim_buf_delete(bufnr, {})
																end,
																50
														)
												end
										}
								)
						else
								-- If it's a normal file, then reopen the terminal, then switch back to the newly opened window
								-- This gives the appearance of the window opening independently of the terminal
								require("toggleterm").toggle(0)
								vim.api.nvim_set_current_win(winnr)
						end
				end,
				block_end = function()
						-- After blocking ends (for a git commit, etc), reopen the terminal
						require("toggleterm").toggle(0)
				end
		}
}
```
2. Try to open a file with `nvim` inside `toggleterm`

**Desktop:**
 - Windows 10 Home 21H2
 - NVIM v0.9.0-dev-1219+g773febc46

**Comment by willothy** [comment]
Thanks for letting me know, I'll look into this and try to get a fix pushed ASAP.

**Comment by minego** [comment]
This happens without toggleterm as well. I have a very simple setup and I had the same behavior on windows.

**Comment by willothy** [comment]
It's been tested / developed solely on Linux so far and I haven't seen this issue, but I'll be testing on Windows today and trying to find a fix. Sorry about that!

**Comment by willothy** [comment]
Ok, I think this is likely related to the server name on Windows not being escaped properly, as it's often a pretty odd path with lots of backslashes like `\\.\pipe\nvim.24392.0`. Should be a relatively quick fix, definitely will be pushed by EOD today.

**Comment by willothy** [comment]
Fix pushed with [362bd0e](https://github.com/willothy/flatten.nvim/commit/362bd0ebe6b0b6961044eaeb3e71956a46f125e4), see if that works :)

**Comment by minego** [comment]
Seems to work for me, at least doing some quick tests.

**Comment by willothy** [comment]
Gotcha, looking into that now - seems like spaces aren't always escaped so I'll have to do that for Windows as well.

**Comment by willothy** [comment]
Should be all good now! Let me know.

**Comment by luiz00martins** [comment]
Working fine for me :)

ty ❤️
