### ISSUE TITLE
[question]: what plugin was used to display the `cmdline` popup

### ISSUE THREAD

**Issue by Clumsy-Coder** [willothy/flatten.nvim#24]
unrelated to this plugin.

But what plugin was used to display the `cmdline` like it was from telescope?

![image](https://user-images.githubusercontent.com/19594044/226506757-1254673e-0352-4300-bd13-d32af9986402.png)

Thanks

**Comment by willothy** [comment]
> unrelated to this plugin.
> 
> 
> 
> But what plugin was used to display the `cmdline` like it was from telescope?

It's noice.nvim: https://github.com/folke/noice.nvim

**Comment by Clumsy-Coder** [comment]
And the dropdown suggestions?
