### ISSUE TITLE
compare to drop in vim-terminal-help

### ISSUE THREAD

**Issue by Konfekt** [willothy/flatten.nvim#26]
Hello, how about relating it to the drop command of [vim-terminal-help](https://github.com/skywind3000/vim-terminal-help/)?

**Comment by willothy** [comment]
> Hello, how about relating it to the drop command of [vim-terminal-help](https://github.com/skywind3000/vim-terminal-help/)?

Hi, I'm not quite sure what you mean... with Flatten there's no need for a special command to open files in the current instance.

**Comment by Konfekt** [comment]
Hello, to me  it looks like an additional `alias nvim=drop` on `TerminalOpen`.

**Comment by willothy** [comment]
Yeah, I understand that, but I don't see why it's necessary...

**Comment by Konfekt** [comment]
Thank you, so to me drop in vim-terminal-help achieves what nvim achieves in flatten.nvim. I guess it is somewhat more cautious but also less intuitive to the same end.

**Comment by willothy** [comment]
Ohh, I misunderstood the question, my bad. Yes, flatten essentially does the same thing as the drop command, but it's integrated fully into Neovim and offers more features such as blocking and piping into buffers from the terminal.
