### ISSUE TITLE
How to use it with akinsho/toggleterm.nvim

### ISSUE THREAD

**Issue by throwaway69420-69420** [willothy/flatten.nvim#28]
**Is your feature request related to a problem? Please describe.**
I want to use it with toggleterm instead of inbuilt neovim terminal

**Describe the solution you'd like**
Some integration of this plugin and the toggleterm plugin

**Comment by willothy** [comment]
Check out the "advanced configuration" section of the readme! That example shows how to use toggleterm with flatten :)

**Comment by willothy** [comment]
I just added a feature that allows you to open the new file(s) in the alternate window, which makes toggleterm integration significantly easier and better.
