### ISSUE TITLE
Manpage Format is Incorrect

### ISSUE THREAD

**Issue by austinliuigi** [willothy/flatten.nvim#32]
**Describe the bug**
I set my default manpager to neovim by adding this to my .bashrc or .zshrc: `export MANPAGER='nvim +Man!'`

When opening a man page through a neovim terminal buffer with flatten.nvim loaded, the man page expectedly loads in the current neovim instance, but the format is messed up (see the screenshots below).

**To Reproduce**
1. Add `export MANPAGER='nvim +Man!'` to shell config
2. Open a terminal buffer in neovim
3. `man ls`

**Screenshots**
<div align="center">

`man ls` from the shell

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/230663413-3ec0f5ff-9ceb-4c33-ba62-04be7a7c396d.png">

</div>

<br>
<br>

<div align="center">

`man ls` from neovim terminal

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/230663733-b9701b59-30e7-48b7-a529-0a88b01fd111.png">

</div>

**Desktop (please complete the following information):**
 - macOS Monterey 12.5 (M1 Macbook Air)
 - NVIM v0.9.0-dev-1326+g7c8c15507   

**Additional Context**
After looking around, the simple issue is that the `Man!` command isn't being run after flatten opens the man page in the current neovim instance. Could allowing `nvim +<cmd>` work with flatten?

**Comment by willothy** [comment]
This is something I've been looking into - definitely Manpage support is something I could hard code as an edge case, but in terms of supporting command pass-through I haven't yet figured out a way to do that. I am actively looking though and will absolutely implement that when I'm able.

I'll look for a solution for manpages in the short term though, thanks for reporting! 

Until then, probably best to just use `Man <topic>` from the parent instance's command-line.

**Comment by davidmh** [comment]
> in terms of supporting command pass-through I haven't yet figured out a way to do that

This is such a great coincidence, I was about to post this in a discussion thread, but I think it's relevant enough to post it here.

I'm looking to solve a very similar problem, and I found a way to read all the arguments passed to the nested nvim instance.

I'm using the `v:argv` variable, which sounds the same as the `argv` function, exept that `v:argv` includes way more data.

For example, when open neovim in diff mode:

```
nvim -d /tmp/a/README.md /tm/b/README.md
```

I get the following through `vim.v.argv`:

```lua
{ "<HOME>/.nix-profile/bin/nvim",
  "--cmd", "let g:loaded_node_provider=0 | let g:loaded_python_provider=0 | let g:python3_host_prog='/nix/store/2j5i0n338vrw9w1jwhmfgfxhnbncr27h-neovim-0.8.1/bin/nvim-python3' | let g:ruby_host_prog='/nix/store/2j5i0n338vrw9w1jwhmfgfxhnbncr27h-neovim-0.8.1/bin/nvim-ruby'",
  "--cmd", "set packpath^=/nix/store/vncf2y1mpg3m8iii6dngmjvsinb732sg-vim-pack-dir",
  "--cmd", "set rtp^=/nix/store/vncf2y1mpg3m8iii6dngmjvsinb732sg-vim-pack-dir",
  "-d", "file-a.txt", "file-b.txt" }
```

Which gets lets me know that `-d` was trying to start a diff mode for the passed files.

I haven't figured out how to get only the commands actually passed by the user. But for the time being, that does what I need.

See my fork: https://github.com/davidmh/flatten.nvim/commit/311b4a2f22f0e7d9fbb5659adb65d4c3a232ee83

And this is how I use it: https://github.com/davidmh/dot-files/blob/main/nvim/fnl/own/plugin/flatten.fnl#L20-L30

Some things I haven't worked through, which I like to address before sending a PR:

- [ ] Get the actual commands passed by the user, not the extra commands shown in the output
- [ ] Have options like `-b` automatically enable blocking.
        In my use case, the diff mode is meant to be used with the [approvals](https://github.com/approvals/ApprovalTests.Ruby#workflow-using-vimdiff)

What do you think?

**Comment by willothy** [comment]
Thank you so much! That's super helpful, will look through your fork and working v:argv tomorrow.

As far as a PR goes, that would be very welcome, but I would like to avoid adding argument flags that aren't already included, so that using flatten is as much like using default neovim as possible. I would consider adding args for specific use cases such as blocking if enough people seem to prefer that to setting a global though, so if you submit a PR it would be ideal for the functionality to be enabled by a global or module-local var instead of an argument directly, so that I/we can decide on which direction to go in based on how the general user base responds to the idea.

Thanks!

**Comment by davidmh** [comment]
That makes sense, maybe a better way to enable blocking programmatically would be to introduce a callback function to determine the blocking before the files are sent from within the nested session.

**Comment by davidmh** [comment]
> As far as a PR goes, that would be very welcome, but I would like to avoid adding argument flags that aren't already Neovim args, so that using flatten is as much like using default Neovim as possible

I'm just re-reading this. The flag I mentioned (-b) already exists in neovim, what I was proposing was to opt out of flatten through a config option in the flatten config. The user would start neovim as they always do.

I'll tune up the fork to include a new callback: `config.callbacks.should_block(vim.v.argv)` to be used as a fallback to `vim.g.flatten_wait`.

I would be happy to also work on dispatching other commands, like the `+Man something` in this issue.

**Comment by willothy** [comment]
Yes, sorry, I should've been more clear - I meant that I'd like to keep all arguments the same functionally as well as semantically, but it seems like opting out through a config option would work very well. Thank you for contributing, I'll review the PR today!
