### ISSUE TITLE
Should avoid opening files in windows containing special buffers (`&buftype != ''`)

### ISSUE THREAD

**Issue by Bekaboo** [willothy/flatten.nvim#42]
**Is your feature request related to a problem? Please describe.**
It seems that currently flatten.nvim will open files in users' previous windows no matter what buffer is originally associated  in that window. This can be an issue when users have two terminal windows opening side by side and try to open a file inside one of the terminals since the file opened will be displayed in the window for another terminal.

**Describe the solution you'd like**
Find the first window that is not associate with a special buffer (`vim.bo.bt == ''`) and open the file in that window.

**Describe alternatives you've considered**
N/A

**Additional context**

There are some screenshots that explain the issue:

1. Two terminals opened side by side:
    ![image](https://user-images.githubusercontent.com/76579810/231847236-0c07d532-5810-44c8-b37a-066504011b92.png)

2. Opening files from the terminal on the right (with the window on the left as the previous window accessed):

    ![image](https://user-images.githubusercontent.com/76579810/231847477-d4e4df22-fd92-47f1-96fc-aaded49e1564.png)

3. File opened on the left window, taking the place of the first terminal, which is not expected:

    ![image](https://user-images.githubusercontent.com/76579810/231847621-6ae4367f-ff8a-49e5-9f88-847db4d42d2f.png)

**Comment by willothy** [comment]
That's a good point, I'll look into implementing that soon.
