### ISSUE TITLE
Errors out when calling `setup` without any parameters

### ISSUE THREAD

**Issue by utilyre** [willothy/flatten.nvim#43]
**Describe the bug**
The title.

**To Reproduce**
1. Put `require("flatten").setup()` in your config.

**Expected behavior**
It should just use the default config.

**Additional context**
Although using something like the `opts` table or `config = true` in lazy.nvim is recommended, I think it's better not to throw when there's no config table provided in `setup`.

**NOTE**: I'm just gonna open a PR to fix.

**Comment by willothy** [comment]
Thanks! I definitely should've been doing this, appreciate the fix.
