### ISSUE TITLE
Provide options for when Wezterm/kitty windows should nest

### ISSUE THREAD

**Issue by ttytm** [willothy/flatten.nvim#56]
**Describe the bug**

Currently, I'm pinning `commit = "d92c93959e9ac52a00002d6fd64c2d2ca5dd7192",` since one of the changes afterwards includes a regression that will close a neovim instance when trying to open nvim in another tab of a terminal that already has a running nvim instance. It would be necessary to open another terminal and run it to not have it closed. 
A fix would be superb - here and then there always comes up a use-case for terminal tabs :).

**System**
 - Linux, deb based
 - Neovim Nightly
 - Tested with kitty and wezterm tabs.

**Comment by willothy** [comment]
I'm not sure I understand what you're describing, could you provide a list of repro steps and/or a video? I'll look into it asap once I have some more info. Thanks for reporting :)

**Comment by tobealive** [comment]
https://github.com/willothy/flatten.nvim/assets/34311583/1664f92f-1c7c-401b-9dce-bcda0c1d0cd0

Hopefully this makes it clear, else please let me know @willothy .
It shows: opeining nvim in a new kitty terminal without issues. Then I'm trying to do it in another tab but it immediately closes on me, trying this multiple times. 

Same for wezterm. 

It doesn't happen with the mentioned commit. 

I bisect and add the exact commit.

**Comment by tobealive** [comment]
Ahh, I see 
```lua
	one_per = {
        kitty = true, -- Flatten all instance in the current Kitty session
        wezterm = true, -- Flatten all instance in the current Wezterm session
    },
``` 
was added.

Didn't notice this as breaking change or opt-in feature.

**Comment by willothy** [comment]
Ah, yes I should've marked it as breaking. That's my bad, I was perhaps a bit too hasty merging that.

**Comment by willothy** [comment]
Actually I'd like to leave this open until I have a PR adding some more options, just as a sort of to-do :)

**Comment by willothy** [comment]
For now you should be able to customize the pipe_path function to suit your needs. Returning nil from that will allow the instance to open. Other than that, what options would be helpful? I'm not quite sure what to add for this.
