### ISSUE TITLE
Commits on August 10 Don't respect the window --> open setting

### ISSUE THREAD

**Issue by jam1015** [willothy/flatten.nvim#66]
**Describe the bug**
I open a terminal in neovim and open a random file, in my case `~/haha.md`.    My setting says to open it in the current window/tab but a new tab is opened instead.

**To Reproduce**
Install  flatten with  Lazy.nvim as you normally would.  Open a neovim terminal and enter `nvim [some file]`

**Expected behavior**
File should open in the same tab/window.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal emulator / nvim GUI: Kitty
 - Neovim Version: 0.9.1

**Additional context**
The problem is solved by going to commits from previous days; [07e9496191653587336b4c8f8cab02e5c34c7c44](https://github.com/willothy/flatten.nvim/commit/07e9496191653587336b4c8f8cab02e5c34c7c44) works as expected

**Comment by willothy** [comment]
Windows and tabs are very different things in Vim, there may be some confusion here. Please provide a minimal init file so that i can help figure this out :)
