### ISSUE TITLE
When there is space in the filename the filename passed to neovim is escaped

### ISSUE THREAD

**Issue by linsui** [willothy/flatten.nvim#70]
**Describe the bug**
Run `nvim "a b c"` in nvim terminal, a `a\ b\ c` file is opened instead. Out of the nvim the correct `a b c` is opened.

**To Reproduce**
1. Open the terminal in nvim
2. Run `nvim "a b c"`

**Expected behavior**
The correct file name is passed to nvim.

**Screenshots**
If applicable, add screenshots and/or videos to help explain your problem.

**Minimal Init**
Please provide a minimal init to quickly reproduce the issue.

**Desktop (please complete the following information):**
 - OS NixOS
 - Terminal emulator / nvim GUI
 - Neovim Version 0.9.1

**Additional context**

**Comment by willothy** [comment]
Please provide a minimal init that can reproduce this, I cannot repro with my config.
